---
- set_fact:
    certs_to_copy:
        - DSTRootCAX3.cer
        - isrgrootx1.cer
        - LetsEncryptAuthorityX3.cer
        - LetsEncryptAuthorityX4.cer
  when: not letsencrypt_staging

- set_fact:
    certs_to_copy:
        - fakelerootx1.cer
        - fakeleintermediatex1.cer
  when: letsencrypt_staging
- include: install.yml

- name: copy root certificates
  copy:
    src: "{{ item }}"
    dest: "{{ letsencrypt_base_dir}}/{{ letsencrypt_domain }}/"
  with_items: "{{ certs_to_copy }}"


- include: issue.yml

- name: install the certificate
  command: >
    {{ letsencrypt_base_dir }}/acme.sh --install-cert
      -d "{{ letsencrypt_domain }}"
      --certpath "{{ letsencrypt_install.cert_path }}"
      --keypath "{{ letsencrypt_install.key_path }}"
      --fullchainpath "{{ letsencrypt_install.fullchain_path }}"
      --reloadcmd "{{ letsencrypt_reloadcmd }}"
  when: letsencrypt_install_mode == "install" and issueW.changed

- name: deploy the certificate
  command: >
    {{ letsencrypt_base_dir }}/acme.sh --deploy
      -d "{{ letsencrypt_domain }}"
      --deploy-hook "{{ letsencrypt_deploy.staging_hook if letsencrypt_staging else letsencrypt_deploy.hook }}"
  when: letsencrypt_install_mode == "deploy" and (issueW.changed or issueS.changed) and letsencrypt_deploy.hook != "freeipa" and letsencrypt_deploy.staging_hook != "freeipa_staging"

- include: freeipa.yml
  when: letsencrypt_deploy.hook == "freeipa" and letsencrypt_deploy.staging_hook == "freeipa_staging"
