---
- include: install.yml

- name: copy root certificates
  copy:
    src: "{{ item }}"
    dest: "{{ letsencrypt_base_dir}}/{{ letsencrypt_domain }}/"
  with_items: "{{ letsencrypt_staging | ternary(certs_staging, certs_prod) }}"

- name: remove root certificates
  file:
    path: "{{ item }}"
    state: absent
  with_items:  "{{ letsencrypt_staging | ternary(certs_prod, certs_staging) }}"

- include: issue.yml

- name: install the certificate
  command: >
    {{ letsencrypt_base_dir }}/acme.sh --install-cert
      -d "{{ letsencrypt_domain }}"
      --certpath "{{ letsencrypt_install.cert_path }}"
      --keypath "{{ letsencrypt_install.key_path }}"
      --fullchainpath "{{ letsencrypt_install.fullchain_path }}"
      --reloadcmd "{{ letsencrypt_reloadcmd }}"
  when: letsencrypt_install_mode == "install" and issueW.changed

- name: deploy the certificate
  command: >
    {{ letsencrypt_base_dir }}/acme.sh --deploy
      -d "{{ letsencrypt_domain }}"
      --deploy-hook "{{ letsencrypt_deploy.staging_hook if letsencrypt_staging else letsencrypt_deploy.hook }}"
  when: letsencrypt_install_mode == "deploy" and (issueW.changed or issueS.changed) and letsencrypt_deploy.hook != "freeipa" and letsencrypt_deploy.staging_hook != "freeipa_staging"

- include: freeipa.yml
  when: letsencrypt_deploy.hook == "freeipa" and letsencrypt_deploy.staging_hook == "freeipa_staging"
